# Generated by Django 5.2.4 on 2025-07-26 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventbooking',
            unique_together=set(),
        ),
    ]
