# Generated by Django 5.2.4 on 2025-07-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_eventbooking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('meeting_request', 'Meeting Request'), ('meeting_response', 'Meeting Response'), ('announcement', 'Announcement'), ('booking_cancellation', 'Booking Cancellation'), ('booking_update', 'Booking Update')], max_length=50),
        ),
    ]
